#    Uncertainty-Analysis-Toolkit-for-Metos3d can be used to generate option files for Metos3d
#    and interpret Metos3d output data.
#    Copyright (C) 2022  Tom L. Hauschild
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
# distribution attributes
distributions:
  number: 2
  D0:
    type: normal
    mean: 0.0
    variance: 1.75
    sample_size: 100
  D1:
    type: normal
    mean: 0.0
    variance: 1.75
    sample_size: 100

# the output directory for the generated data
output_directory: ""
# option -> option1.txt, option2.txt, option3.txt, ...
file_name: "new_option"
# if set to "True" the program will generate arguments for the mpirun command used in batch files to run metos3d
mpirun:
  generate: True
  optionfiles_path: "../metos3d-parameter-generator/"
  program_path: "./metos3d-simpack-N.exe"

option_file_path: "resources/option.txt"
# use %DX% as the distribution variable with X being the distribution number
model:
  Metos3dDebugLevel: "%D0%+%D1%"