# distribution attributes; you have to set the number of distribution you use (number = x). 
# Name the distributions in the pattern "DX" with X being 0 for the first distribution
# counting upwards for following distributions
distributions:
  number: 2                # number of distributions (max. 3)
  D0:
    sample_size: 3         # sample size
    type: lognormal        # distribution type
    mu: -3.925             # mu of the distribution
    sigma: 0.01            # sigma of the distribution
    lower_bound: 0.01
    upper_bound: 0.05
    tries: 1               # number of tries to generate one parameter value (generation fails if number is out of bounds)
    value_on_fail: 0.02    # parameter value if generation fails
    save_in_csv: True      # save parameter values in csv file
  D1:
    sample_size: 3         # sample size
    type: lognormal        # distribution type
    mu: 3.38785            # mu of the distribution
    sigma: 0.1634          # sigma of the distribution
    lower_bound: 15.0
    upper_bound: 60.0
    tries: 1               # number of tries to generate one parameter value (generation fails if number is out of bounds)
    value_on_fail: 30.0    # parameter value if generation fails
    save_in_csv: True      # save parameter values in csv file
# the output directory for the generated data
output_directory: "option_files/"
# the path to the template option file
option_file_path: "resources/template_option_N.txt"
# option -> option1.txt, option2.txt, option3.txt, ...
file_name: "option"
# if set to "True" the program will generate arguments for the mpirun command used in batch files to run metos3D
mpirun:
  generate: True
  optionfiles_path: "../metos3d-parameter-generator/option_files/"
  program_path: "./metos3d-simpack-N.exe"
  options: "-np 128"

# use %DX% as the distribution variable with X being the distribution number
model:
  Metos3DParameterValue: "%D0%,%D1%,0.5,30.0,0.858"
  Metos3DTimeStepCount: 90
  Metos3DTimeStep: 0.0111111111111111
  Metos3DSpinupCount: 3000
  Metos3DMatrixCount: 12
  Metos3DMatrixInputDirectory:  "data/TMM/2.8/Transport/Matrix5_4/32dt/"